/**
 * prepare.ts — The fixed API surface for generated training code.
 * This is the "prepare.py" equivalent: data loading, evaluation, jax-js re-exports.
 * Generated code receives everything here as globals.
 */

import { numpy as np, nn, random, tree, blockUntilReady, valueAndGrad, jit, vmap, grad } from '@jax-js/jax';
import { adamw, applyUpdates } from '@jax-js/optax';
import { DataLoader } from './data/loader';
import { lrMultiplier } from './train/schedule';

export type Params = { [key: string]: np.Array };
export type ForwardFn = (params: Params, inputIds: np.Array) => np.Array;

export type StepMetrics = {
	step: number;
	loss: number;
	elapsed: number;
};

export type TrainResult = {
	params: Params;
	forward: ForwardFn;
	vocabSize: number;
	batchSize: number;
	seqLen: number;
};

export type TrainCallbacks = {
	trainData: DataLoader;
	valData: DataLoader;
	trainSeconds: number;
	signal: AbortSignal;
	onStep: (m: StepMetrics) => void;
	onReturn: (r: TrainResult) => void;
};

function yieldToUI(): Promise<void> {
	return new Promise((resolve) => requestAnimationFrame(() => resolve()));
}

/**
 * Evaluate validation bits-per-byte using a provided forward function.
 * This is fixed infrastructure — not generated by Claude.
 */
async function evaluate(
	params: Params,
	forwardFn: ForwardFn,
	vocabSize: number,
	valData: DataLoader,
	batchSize: number,
	seqLen: number
): Promise<number> {
	valData.reset();
	const evalTokens = Math.min(valData.length, 100_000);
	const tokensPerBatch = batchSize * seqLen;
	const numSteps = Math.max(1, Math.floor(evalTokens / tokensPerBatch));

	let totalNats = 0;
	let totalTokens = 0;

	for (let i = 0; i < numSteps; i++) {
		const batch = valData.nextBatch(batchSize, seqLen);
		const logits = forwardFn(params, batch.input);
		const logProbs = nn.logSoftmax(logits, -1);
		const targets = nn.oneHot(batch.target.reshape([-1]), vocabSize);
		const flatLogProbs = logProbs.reshape([-1, vocabSize]);
		const nll = flatLogProbs.mul(targets).sum().neg();
		await blockUntilReady(nll);
		totalNats += (await nll.jsAsync()) as number;
		totalTokens += batchSize * seqLen;
	}

	return totalNats / (Math.LN2 * totalTokens);
}

/** The full set of globals injected into generated code. */
export function getPrepareGlobals() {
	return {
		np, nn, random, tree, blockUntilReady, valueAndGrad,
		jit, vmap, grad,
		adamw, applyUpdates,
		evaluate, lrSchedule: lrMultiplier, yieldToUI,
		VOCAB_SIZE: 256,
	};
}
